#!/bin/bash -e
cd "$( dirname "${BASH_SOURCE[0]}" )"

pushd engine > /dev/null
NODE_ENV=development npm install
npm run build
npm pack
popd > /dev/null

for game in test-games/*; do
    pushd "$game" > /dev/null
    if [ -f package.json ]; then
        echo installing "$game"
        NODE_ENV=development npm uninstall engine
        NODE_ENV=development npm install engine@file:../../engine/jellyfish.js-0.0.2.tgz
        NODE_ENV=development npm ci
        npm run build
    fi
    popd > /dev/null
done
