name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install engine dependencies
      run: npm ci
      working-directory: engine
    - name: Build engine
      run: npm run build
      working-directory: engine
    - name: Test engine
      run: npm test
      working-directory: engine
    - name: Run test games
      run: |
        set +e
        for game in test-games/*; do
          echo
          printf '%*s\n' "$COLUMNS" '' | tr ' ' -
          echo "Testing game: $game"
          pushd "$game" > /dev/null
          npm install
          npm run build
          timeout 5 npm start > /dev/null
          if [ ! "$?" -eq 124 ]; then
            echo "Game $game failed to run for 5 seconds without errors"
            exit 1
          fi
          popd > /dev/null
        done
