name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install engine dependencies
      run: npm ci
      working-directory: engine
    - name: Build engine
      run: npm run build
      working-directory: engine
    - name: Test engine
      run: npm test
      working-directory: engine
    - name: Pack engine
      run: |
        npm pack
        cp "$(printf '%s\n' jellyfish.js-*.tgz | sort -Vr | head -n1)" jellyfish.js.tgz
      working-directory: engine
    - name: Run test games
      run: |
        for game in test-games/*; do
          echo
          printf '%*s\n' "$COLUMNS" '' | tr ' ' -
          echo "Testing game: $game"
          pushd "$game" > /dev/null
          npm uninstall engine
          npm install engine@file:../../engine/jellyfish.js.tgz
          npm ci
          npm run build
          timeout 5 npm start > /dev/null || ret=$?
          if [ "$ret" -ne 124 ]; then
            echo "Game $game failed to run for 5 seconds without errors"
            exit 1
          fi
          popd > /dev/null
        done
